// RobotBuilder Version: 2.0BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.commands;
import edu.wpi.first.wpilibj.command.BBCommand;
import edu.wpi.first.wpilibj.command.Scheduler;

import org.usfirst.frc330.Robot;
import org.usfirst.frc330.commands.commandgroups.ClimbDeploy;
import org.usfirst.frc330.util.Logger;
import org.usfirst.frc330.util.Logger.Severity;

/**
 *
 */
public class ClimbDeployVerify extends BBCommand {

    boolean twoButtonComplete = false;

    public ClimbDeployVerify() {

    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        twoButtonComplete = false;
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        if(Robot.oi.gamePad.getRawAxis(3)>0.9 && !twoButtonComplete) {
            Scheduler.getInstance().add(new ClimbDeploy());
            twoButtonComplete = true;
            Logger.getInstance().println("Second deploy button detected; deploying.", Severity.INFO);
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        if(!twoButtonComplete){
            Logger.getInstance().println("Command ended without decond deploy button being detected", Severity.WARNING);
        }
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        if(!twoButtonComplete){
            Logger.getInstance().println("Command ended without decond deploy button being detected", Severity.WARNING);
        }
    }
}
