// RobotBuilder Version: 2.0BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.commands;
import edu.wpi.first.wpilibj.command.BBCommand;
import org.usfirst.frc330.Robot;
import org.usfirst.frc330.constants.ChassisConst;
import org.usfirst.frc330.constants.LiftConst;

/**
 *
 */
public class DrivePogoAndDriveTrain extends BBCommand {

    public DrivePogoAndDriveTrain() {

        requires(Robot.lift);
        requires(Robot.chassis);

    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {

    }

    double left, right, pogoSpeed, pogoRatio;
    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        left = Robot.oi.getDriverL().getY();
        right = Robot.oi.getDriverR().getY();
        pogoSpeed = (left + right)/2;
        pogoRatio = LiftConst.pogoMaxSpeed / ChassisConst.LowGearMaxSpeed * 2.5 ; //AP fudge factor 3/1/19

        Robot.chassis.tankDrive(-pogoSpeed*pogoRatio, -pogoSpeed*pogoRatio);
        Robot.lift.pogoDrive(pogoSpeed);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return (Robot.oi.driverR.getRawButton(3));
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.chassis.tankDrive(0, 0);
        Robot.lift.pogoDrive(0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        end();
    }
}
