// RobotBuilder Version: 2.0BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.commands;

import edu.wpi.first.wpilibj.command.BBConditionalCommand;
import org.usfirst.frc330.Robot;
import org.usfirst.frc330.commands.commandgroups.EjectBall;
import org.usfirst.frc330.constants.LiftConst;
import org.usfirst.frc330.subsystems.Pickup.GamePiece;

/**
 *
 */
public class SetLiftPositionDefense extends BBConditionalCommand {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public SetLiftPositionDefense() {
      super(new SetLiftPosition(LiftConst.DeployBallLow), new SetLiftPosition(LiftConst.defense));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

    }

    @Override
    protected boolean condition(){
        if(Robot.pickup.getLastPickup() == GamePiece.BALL){
            return true;
        }
        else{
            return false;
        }
    }
}
