// RobotBuilder Version: 2.0BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.commands.commandgroups;

import edu.wpi.first.wpilibj.command.BBCommandGroup;

import org.usfirst.frc330.commands.*;
import org.usfirst.frc330.constants.*;
import org.usfirst.frc330.subsystems.*;

/**
 *
 */
public class BallPickupLoadStation extends BBCommandGroup {


    public BallPickupLoadStation() {
        //if the ball is in the pickup, loop until it is gone
    	addSequential(new LoopIfWeHaveBall());
        //if the pickup has no ball in it, execute the following code:
        
        //Prep Pickup
        addSequential(new OpenClaw());
        addSequential(new RollerOnBall());

        //lower lift and pickup to ball intake positon
        addParallel(new SetLiftPosition(LiftConst.BallPickupPlayer));
        addSequential(new SetHandAngle(HandConst.ballPickupHumanPlayer));

        //close claw once we have ball
        addSequential(new WaitCommand(0.4)); //this can be changed if needed
        addSequential(new SensorCloseClawBall());

        //now that the ball is in the claw, we turn on the rollers until it is secure
        addSequential(new RollerUntilBall());

        //once everything is finished, enter defense mode
        addSequential(new Defense());
        addSequential(new IsFinishedFalse());
        //VERIFY ejo 2.18.19
    } 
}
