// RobotBuilder Version: 2.0BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.commands.commandgroups;

import edu.wpi.first.wpilibj.command.BBCommandGroup;
import org.usfirst.frc330.commands.*;
import org.usfirst.frc330.commands.drivecommands.*;
import org.usfirst.frc330.constants.ChassisConst;
import org.usfirst.frc330.constants.LiftConst;

/**
 *
 */
public class Climb extends BBCommandGroup {


    public Climb() {
        addSequential(new ShiftLow());
        addSequential(new SetLiftPosition(LiftConst.PogoDrive, LiftConst.tolerance, true, 1));
        //addSequential(new DrivePogo(LiftConst.PogoDriveDistance));  //JR DISABLED 2/24/19 until time to tune pogo
        addSequential(new DrivePogoAndDriveTrain());
        addSequential(new ConditionalPogoRetract());
        //addSequential(new DriveDistanceAtCurAngle(ChassisConst.PlatformDrive, 1.0, 3.0, false, ChassisConst.DriveLow, ChassisConst.GyroDriveLow)); //JR DISABLED 2/24/19 until time to tune drivetrain
        addSequential(new TankDrive(0.4));
        //double distance, double tolerance, double timeout, boolean stopAtEnd, DrivePIDGains driveGains, DrivePIDGains gyroGains
    } 
}
